In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [95]:
A = np.mat('1 2 -2; 1 1 1; 2 2 1')
b = A.dot([1,2,3]).T

In [111]:
def jacobi(A,b,epsilon):
    Pinv = diag(1/(diag(A)))
    I = diag(ones(len(A)))
    B = I - Pinv.dot(A)
    print("B is", B)
    print("eigenvalues: ",eig(B)[0])
    g = Pinv.dot(b)
    x = zeros(len(A))
    while(norm(b-A.dot(x))>epsilon):
        x = B.dot(x) + g
        print(x[:,0])
    return x[:,0]

In [112]:
x = jacobi(A,b,0.00000004)

B is [[ 0. -2.  2.]
 [-1.  0. -1.]
 [-2. -2.  0.]]
eigenvalues:  [-6.16610918e-06+1.06799587e-05j -6.16610918e-06-1.06799587e-05j
  1.23322184e-05+0.00000000e+00j]
[[-1.]
 [ 6.]
 [ 9.]]
[[ 5.]
 [-2.]
 [-1.]]
[[1.]
 [2.]
 [3.]]


SyntaxError: invalid syntax (<ipython-input-70-6d88e4e6ecf8>, line 7)